import { useCallback, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, FilePlus2, FileText, Folder, FolderInput, FolderOpen, FolderPlus, Pencil, Save, Trash2, Upload, X } from "lucide-react";
import { open } from "@tauri-apps/plugin-dialog";
import { createFile, createFolder, deletePath, getXamppRoot, listDirectory, readFile, renamePath, uploadFiles, uploadFolder, writeFile } from "@/lib/ipc";
import type { FileEntry } from "@/lib/types";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/button";
import { ConfirmActionDialog } from "@/components/ui/ConfirmActionDialog";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { toast } from "sonner";
import { useLocation } from "react-router-dom";

type DeploymentWorkspaceState = { deploymentPath?: string; deploymentName?: string };
type FileAction = "file" | "folder" | "rename";

export default function FileBrowser() {
  const location = useLocation(); const workspace = (location.state as DeploymentWorkspaceState | null) ?? {};
  const [currentDir, setCurrentDir] = useState<string | null>(null); const [selectedFile, setSelectedFile] = useState<string | null>(null); const [content, setContent] = useState<string | null>(null); const [filter, setFilter] = useState(""); const [confirmSave, setConfirmSave] = useState(false); const [deleteTarget, setDeleteTarget] = useState<FileEntry | null>(null); const [fileAction, setFileAction] = useState<FileAction | null>(null); const [actionTarget, setActionTarget] = useState<FileEntry | null>(null); const [actionName, setActionName] = useState("");
  const queryClient = useQueryClient(); const rootQuery = useQuery({ queryKey: ["xampp-root"], queryFn: getXamppRoot }); const directoryQuery = useQuery({ queryKey: ["files", currentDir], queryFn: () => listDirectory(currentDir!), enabled: !!currentDir }); const fileQuery = useQuery({ queryKey: ["file-content", selectedFile], queryFn: () => readFile(selectedFile!), enabled: !!selectedFile });
  const refreshDirectory = () => queryClient.invalidateQueries({ queryKey: ["files", currentDir] });
  useEffect(() => { if (rootQuery.data && !currentDir) setCurrentDir(workspace.deploymentPath ?? rootQuery.data); }, [rootQuery.data, currentDir, workspace.deploymentPath]);
  useEffect(() => { if (fileQuery.data !== undefined) setContent(fileQuery.data); }, [fileQuery.data]);
  const hasUnsavedChanges = content !== null && content !== fileQuery.data; const root = rootQuery.data?.replace(/\\+$/, "").toLowerCase(); const isAtRoot = !!root && currentDir?.replace(/\\+$/, "").toLowerCase() === root; const visibleEntries = useMemo(() => directoryQuery.data?.filter((entry) => entry.name.toLowerCase().includes(filter.toLowerCase())) ?? [], [directoryQuery.data, filter]);
  const saveMutation = useMutation({ mutationFn: () => writeFile(selectedFile!, content ?? ""), onSuccess: () => { queryClient.setQueryData(["file-content", selectedFile], content ?? ""); refreshDirectory(); toast.success("File saved"); }, onError: (reason: Error) => toast.error(reason.message) });
  const actionMutation = useMutation({ mutationFn: async () => { if (!currentDir || !fileAction) return; if (fileAction === "file") return createFile(currentDir, actionName); if (fileAction === "folder") return createFolder(currentDir, actionName); return renamePath(actionTarget!.path, actionName); }, onSuccess: (result) => { const createdPath = typeof result === "string" && fileAction === "file" ? result : null; const renamedSelected = typeof result === "string" && fileAction === "rename" && selectedFile === actionTarget?.path ? result : null; setFileAction(null); setActionName(""); setActionTarget(null); refreshDirectory(); if (renamedSelected) setSelectedFile(renamedSelected); if (createdPath) setSelectedFile(createdPath); toast.success(fileAction === "rename" ? "Item renamed" : fileAction === "folder" ? "Folder created" : "File created"); }, onError: (reason: Error) => toast.error(reason.message) });
  const deleteMutation = useMutation({ mutationFn: () => deletePath(deleteTarget!.path), onSuccess: () => { if (selectedFile === deleteTarget?.path) { setSelectedFile(null); setContent(null); } setDeleteTarget(null); refreshDirectory(); toast.success("Item deleted"); }, onError: (reason: Error) => toast.error(reason.message) });
  const uploadFilesMutation = useMutation({ mutationFn: (paths: string[]) => uploadFiles(currentDir!, paths), onSuccess: () => { refreshDirectory(); toast.success("Files uploaded"); }, onError: (reason: Error) => toast.error(reason.message) });
  const uploadFolderMutation = useMutation({ mutationFn: (path: string) => uploadFolder(currentDir!, path), onSuccess: () => { refreshDirectory(); toast.success("Folder uploaded"); }, onError: (reason: Error) => toast.error(reason.message) });
  const discardOr = (callback: () => void) => { if (!hasUnsavedChanges || window.confirm("Discard unsaved file changes?")) callback(); };
  const navigate = useCallback((path: string) => discardOr(() => { setSelectedFile(null); setContent(null); setCurrentDir(path); setFilter(""); }), [hasUnsavedChanges]); const openFile = useCallback((path: string) => discardOr(() => setSelectedFile(path)), [hasUnsavedChanges]); const parent = currentDir?.split("\\").slice(0, -1).join("\\");
  const startAction = (action: FileAction, target?: FileEntry) => { setFileAction(action); setActionTarget(target ?? null); setActionName(target?.name ?? (action === "file" ? "untitled.txt" : "new-folder")); };
  const chooseFiles = async () => { try { const picked = await open({ multiple: true, directory: false, title: "Select files to upload" }); const paths = typeof picked === "string" ? [picked] : picked ?? []; if (paths.length) uploadFilesMutation.mutate(paths); } catch { toast.error("Could not open the file picker"); } };
  const chooseFolder = async () => { try { const picked = await open({ multiple: false, directory: true, title: "Select a folder to upload" }); if (typeof picked === "string") uploadFolderMutation.mutate(picked); } catch { toast.error("Could not open the folder picker"); } };
  const actionTitle = fileAction === "rename" ? "Rename item" : fileAction === "folder" ? "Create folder" : "Create file";

  return <div className="flex h-full min-w-0 flex-col p-6"><PageHeader title={workspace.deploymentName ? `Customize ${workspace.deploymentName}` : "File Browser"} description={workspace.deploymentName ? "Create, upload, edit, rename, and delete files in this protected deployment workspace." : "Manage files and folders inside the local XAMPP installation only."} actions={<span className="rounded-md bg-muted px-2.5 py-1.5 font-mono text-xs text-muted-foreground">{workspace.deploymentName ? "Deployment workspace" : rootQuery.data ?? "Loading root…"}</span>} />
    <div className="grid min-h-0 min-w-0 flex-1 grid-cols-1 gap-4 lg:grid-cols-[22rem_minmax(0,1fr)]">
      <section className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="border-b border-border bg-muted/30 p-3"><div className="mb-3 flex items-center gap-2"><Button variant="ghost" size="icon-xs" disabled={isAtRoot} onClick={() => parent && navigate(parent)} aria-label="Go to parent folder"><ArrowLeft /></Button><div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">Current folder</p><p className="truncate font-mono text-xs text-foreground" title={currentDir ?? undefined}>{currentDir ?? "Loading…"}</p></div></div><Input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filter this folder" aria-label="Filter files" /></div><ScrollArea className="min-h-0 flex-1"><div className="p-2">{directoryQuery.isLoading ? <State text="Loading files…" /> : directoryQuery.error ? <State text="Could not read this folder." destructive /> : visibleEntries.length === 0 ? <State text={filter ? "No items match this filter." : "This folder is empty."} /> : visibleEntries.map((entry) => <FileRow key={entry.path} entry={entry} selected={selectedFile === entry.path} onOpen={() => entry.is_dir ? navigate(entry.path) : openFile(entry.path)} onRename={() => startAction("rename", entry)} onDelete={() => setDeleteTarget(entry)} />)}</div></ScrollArea></section>
      <section className="flex min-h-0 min-w-0 flex-col overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="flex flex-wrap items-center gap-2 border-b border-border bg-muted/30 px-4 py-3"><div className="mr-auto"><p className="font-medium">Workspace actions</p><p className="text-xs text-muted-foreground">Changes stay inside the configured XAMPP directory.</p></div><Button variant="outline" size="sm" onClick={() => startAction("folder")}><FolderPlus />Folder</Button><Button variant="outline" size="sm" onClick={() => startAction("file")}><FilePlus2 />File</Button><Button variant="outline" size="sm" onClick={() => void chooseFiles()} disabled={!currentDir || uploadFilesMutation.isPending}><Upload />{uploadFilesMutation.isPending ? "Uploading…" : "Upload files"}</Button><Button variant="outline" size="sm" onClick={() => void chooseFolder()} disabled={!currentDir || uploadFolderMutation.isPending}><FolderInput />{uploadFolderMutation.isPending ? "Uploading…" : "Upload folder"}</Button></div>{selectedFile ? <><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border px-4 py-3"><div className="min-w-0"><p className="text-xs text-muted-foreground">Editing file</p><p className="truncate font-mono text-sm" title={selectedFile}>{selectedFile}</p></div><div className="flex items-center gap-2">{hasUnsavedChanges && <span className="text-xs font-medium text-amber-600 dark:text-amber-400">Unsaved changes</span>}<Button size="sm" onClick={() => setConfirmSave(true)} disabled={!hasUnsavedChanges || saveMutation.isPending}><Save />{saveMutation.isPending ? "Saving…" : "Save"}</Button><Button variant="outline" size="icon-sm" onClick={() => discardOr(() => { setSelectedFile(null); setContent(null); })} aria-label="Close file"><X /></Button></div></div>{fileQuery.isLoading ? <State text="Opening file…" /> : fileQuery.error ? <State text="This file cannot be opened as editable text." destructive /> : <textarea className="min-h-0 flex-1 resize-none bg-background p-4 font-mono text-sm leading-6 text-foreground outline-none" value={content ?? ""} onChange={(event) => setContent(event.target.value)} spellCheck={false} />}</> : <div className="flex h-full flex-col items-center justify-center p-6 text-center"><FolderOpen className="mb-3 size-10 text-muted-foreground" /><h2 className="font-medium">Ready to manage this folder</h2><p className="mt-1 max-w-sm text-sm text-muted-foreground">Select a file to edit it, or use the actions above to add files and folders.</p></div>}</section>
    </div>
    <Dialog open={!!fileAction} onOpenChange={(isOpen) => !isOpen && setFileAction(null)}><DialogContent><DialogHeader><DialogTitle>{actionTitle}</DialogTitle><DialogDescription>{fileAction === "rename" ? "Choose a new name. The file extension is part of the name." : "Names may not contain path separators."}</DialogDescription></DialogHeader><label className="grid gap-2 text-sm"><span className="font-medium">Name</span><Input autoFocus value={actionName} onChange={(event) => setActionName(event.target.value)} onKeyDown={(event) => event.key === "Enter" && actionMutation.mutate()} /><span className="text-xs text-muted-foreground">{fileAction === "file" ? "A new editable text file will be created." : fileAction === "folder" ? "A new folder will be created here." : "Existing items are never overwritten."}</span></label><DialogFooter><Button variant="outline" onClick={() => setFileAction(null)} disabled={actionMutation.isPending}>Cancel</Button><Button onClick={() => actionMutation.mutate()} disabled={!actionName.trim() || actionMutation.isPending}>{actionMutation.isPending ? "Working…" : fileAction === "rename" ? "Rename" : "Create"}</Button></DialogFooter></DialogContent></Dialog>
    <ConfirmActionDialog open={confirmSave} onOpenChange={setConfirmSave} title="Save file changes?" description={`This will overwrite ${selectedFile ?? "the selected file"}.`} confirmLabel="Save file" pending={saveMutation.isPending} onConfirm={() => { saveMutation.mutate(); setConfirmSave(false); }} />
    <ConfirmActionDialog open={!!deleteTarget} onOpenChange={(isOpen) => !isOpen && setDeleteTarget(null)} title={`Delete ${deleteTarget?.name ?? "item"}?`} description={deleteTarget?.is_dir ? "This permanently removes the folder and all files inside it." : "This permanently removes this file."} confirmLabel="Delete permanently" destructive pending={deleteMutation.isPending} onConfirm={() => deleteTarget && deleteMutation.mutate()} />
  </div>;
}

function FileRow({ entry, selected, onOpen, onRename, onDelete }: { entry: FileEntry; selected: boolean; onOpen: () => void; onRename: () => void; onDelete: () => void }) { return <div className={`group flex items-center gap-2 rounded-lg px-2 py-1.5 ${selected ? "bg-primary/10" : "hover:bg-muted"}`}><button onClick={onOpen} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="rounded-md bg-muted p-1.5 text-muted-foreground">{entry.is_dir ? <Folder className="size-4" /> : <FileText className="size-4" />}</span><span className="min-w-0"><span className="block truncate text-sm">{entry.name}</span><span className="block truncate text-[11px] text-muted-foreground">{entry.is_dir ? "Folder" : `${formatBytes(entry.size)} · ${entry.modified || "Unknown date"}`}</span></span></button><div className="flex shrink-0 gap-0.5 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100"><Button size="icon-xs" variant="ghost" onClick={onRename} title="Rename"><Pencil /></Button><Button size="icon-xs" variant="ghost" onClick={onDelete} title="Delete"><Trash2 className="text-destructive" /></Button></div></div>; }
function State({ text, destructive = false }: { text: string; destructive?: boolean }) { return <div className={`flex h-full min-h-40 items-center justify-center p-5 text-center text-sm ${destructive ? "text-destructive" : "text-muted-foreground"}`}>{text}</div>; }
function formatBytes(bytes: number) { return bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(1)} KB`; }
